name: fan
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1
  flutter: ^3.32.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flame: ^1.30.0

  just_audio: ^0.10.4
  just_audio_media_kit: ^2.1.0
  media_kit:
  media_kit_libs_audio:
  media_kit_libs_linux:
  media_kit_libs_windows_audio:

  material_symbols_icons: ^4.2815.1

  stow_plain: ^0.4.0+1
  stow_codecs: ^1.2.0+1
  shared_preferences: ^2.5.3

  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  golden_screenshot: ^3.3.0
  icons_launcher: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/audio/
    - assets/images/fan-assets/

# ./scripts/generate-icons.sh
icons_launcher:
  image_path: "assets/icon/logo.png"
  platforms:
    android:
      enable: true
      adaptive_background_color: "#1a110f"
      adaptive_foreground_image: "assets/icon/logo_android_fg.png"
    ios:
      enable: false
    macos:
      enable: false
    windows:
      enable: true
    linux:
      enable: true
    web:
      enable: true
