name: fan
description: "A new Flutter project."
publish_to: 'none'

# Version code is two digits each for major/minor/patch, and an extra digit for the revision.
# e.g. 1.2.3(.4) => 102034
version: 1.0.2+100021

environment:
  sdk: ^3.8.1
  flutter: ^3.32.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flame: ^1.30.0
  flutter_svg: ^2.2.0

  audio_service: ^0.18.18
  audio_session: ^0.2.2
  just_audio: ^0.10.4
  just_audio_media_kit: ^2.1.0
  media_kit:
  media_kit_libs_audio:

  material_symbols_icons: ^4.2815.1

  stow_plain: ^0.5.1
  stow_codecs: ^1.2.0+1
  shared_preferences: ^2.5.3

  url_launcher: ^6.3.2

  disable_battery_optimizations_latest: ^1.0.0
  material_new_shapes: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  golden_screenshot: ^3.3.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/audio/
    - assets/icon/logo_android_mono.svg
    - assets/images/fan-assets/

# ./scripts/generate-icons.sh
flutter_launcher_icons:
  image_path: "assets/icon/logo.png"
  android: true
  adaptive_icon_background: "#1a110f"
  adaptive_icon_foreground_inset: 24
  adaptive_icon_foreground: "assets/icon/logo_android_fg.png"
  adaptive_icon_monochrome: "assets/icon/logo_android_mono.png"
  ios: true
  image_path_ios: "assets/icon/logo_ios.png"
  web:
    generate: true
    background_color: "#1a110f"
    theme_color: "#ffd2c0"
  windows:
    generate: true
    icon_size: 256
